### ISSUE TITLE
Can't generate sdk for the latest model (version 4.3.8)

### ISSUE THREAD

**Issue by andrexus** [imjoey/ovirt-engine-sdk-go#99] opened 2018-03-31 10:58 UTC
Exception stack trace
```
[INFO] --- exec-maven-plugin:1.2.1:java (generate-code) @ go-sdk ---
ERROR Main - Error while executing the "run" method of tool class "org.ovirt.sdk.go.Tool".
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.ovirt.api.metamodel.tool.Main.main(Main.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: org.ovirt.api.metamodel.concepts.ArrayExpression cannot be cast to org.ovirt.api.metamodel.analyzer.MethodExpression
	at org.ovirt.api.metamodel.analyzer.InputDetailAnalyzer.removePrefix(InputDetailAnalyzer.java:87)
```

**Comment by mwperina** [comment] 2018-04-01 16:49
@machacekondra

**Comment by imjoey** [comment] 2018-04-02 05:25
@andrexus Please update the latest code first, with issue #100 fixed .  After updating, the generator with the model 4.3.8 and metamodel 1.3.0 is works for me. If there still has problems, please offer your metamodel version and the root pom file.

**Comment by imjoey** [comment] 2018-05-28 07:44
@andrexus  I had just re-produce this error. Maybe you ran the `mvn package` under the `./sdk` subdirectory. While `mvn package` command must be running under the root `./` directory.

**Comment by imjoey** [comment] 2018-06-09 03:38
@andrexus As mentioned above, this is actually not a bug. Close it now. If you still have problems, please be free to reopen it.

**Closed by imjoey** 2018-06-09 03:38 UTC
Labels: bug, priority/P1, status/in-comfirmation
